In [1]:
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sc.settings.set_figure_params(figsize=(6,6))

C:\Users\gaura\AppData\Local\Temp\ipykernel_83960\3053215526.py:6: FutureWarning: The method set_figure_params is deprecated and will be removed in the future. Use :func:`scanpy.set_figure_params` instead
  sc.settings.set_figure_params(figsize=(6,6))

In [3]:
import os
print(os.getcwd())

d:\Shreya_visa_docs\colorectal_cancer\Single-cell-immune-landscape-in-cancer

In [4]:
adata = sc.read_h5ad(
    "data/raw/81bd8922-b69a-45ea-9b2a-032c480c0e37.h5ad"
)

In [5]:
adata

AnnData object with n_obs × n_vars = 47107 × 25344
    obs: 'total_counts', 'log1p_total_counts', 'Sample ID', 'PhenoGraph_clusters', 'Patient', 'Primary Site', 'Sample Type', 'Site', 'Tumor Status', 'Treatment', 'donor_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'cell_type_ontology_term_id', 'assay_ontology_term_id', 'suspension_type', 'Author Cell Type', 'is_primary_data', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'total_counts', 'highly_variable', 'gene', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'default_embedding', 'is_pre_analysis', 'neighbors', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_umap'
    layers: None (.X)

In [6]:
adata.obs.head()

,total_counts,log1p_total_counts,Sample ID,PhenoGraph_clusters,Patient,Primary Site,Sample Type,Site,Tumor Status,Treatment,...,Author Cell Type,is_primary_data,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
120703408786358_KG75P2,3496.0,8.159660,KG75P2,10,75,Sigmoid,Primary,NaN,Primary Tumor,True,...,Primary Tumor,True,malignant cell,10x 3' v3,colorectal cancer,female,sigmoid colon,European American,53-year-old stage,mI^Q51qX6n
120703408826100_KG146M2,20505.0,9.928473,KG146M2,35,146,Rectum,Metastasis,Lung,Metastasis,True,...,Metastasis,True,malignant cell,10x 3' v3,colorectal cancer,female,lung,Hispanic or Latin,45-year-old stage,3ud^4DARfj
120703408860572_KG183M,92935.0,11.439667,KG183M,22,183,Sigmoid,Metastasis,Liver,Metastasis,True,...,Metastasis,True,malignant cell,10x 3' v3,colorectal cancer,female,liver,Hispanic or Latin,55-year-old stage,z#2)cw`Sdm
120703409315100_KG146N,42233.0,10.650981,KG146N,6,146,Rectum,Non-Tumor,NaN,Non-Tumor,True,...,Absorptive Precursor,True,early colonocyte,10x 3' v3,normal,female,rectum,Hispanic or Latin,45-year-old stage,MX>JlayPt>
120703409348006_KG146P,59102.0,10.987037,KG146P,7,146,Rectum,Primary,NaN,Primary Tumor,True,...,Primary Tumor,True,malignant cell,10x 3' v3,colorectal cancer,female,rectum,Hispanic or Latin,45-year-old stage,ZM+G?Mik_s

In [7]:
adata.obs.columns.tolist()

['total_counts',
 'log1p_total_counts',
 'Sample ID',
 'PhenoGraph_clusters',
 'Patient',
 'Primary Site',
 'Sample Type',
 'Site',
 'Tumor Status',
 'Treatment',
 'donor_id',
 'development_stage_ontology_term_id',
 'sex_ontology_term_id',
 'self_reported_ethnicity_ontology_term_id',
 'disease_ontology_term_id',
 'tissue_type',
 'tissue_ontology_term_id',
 'cell_type_ontology_term_id',
 'assay_ontology_term_id',
 'suspension_type',
 'Author Cell Type',
 'is_primary_data',
 'cell_type',
 'assay',
 'disease',
 'sex',
 'tissue',
 'self_reported_ethnicity',
 'development_stage',
 'observation_joinid']

In [8]:
adata.var.head()

,total_counts,highly_variable,gene,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000000003,114148.0,False,TSPAN6,False,TSPAN6,NCBITaxon:9606,gene,2396,protein_coding
ENSG00000000005,587.0,False,TNMD,False,TNMD,NCBITaxon:9606,gene,873,protein_coding
ENSG00000000419,104084.0,False,DPM1,False,DPM1,NCBITaxon:9606,gene,1262,protein_coding
ENSG00000000457,21853.0,False,SCYL3,False,SCYL3,NCBITaxon:9606,gene,2916,protein_coding
ENSG00000000460,9196.0,False,C1ORF112,False,FIRRM,NCBITaxon:9606,gene,2661,protein_coding

In [9]:
adata.var.columns.tolist()

['total_counts',
 'highly_variable',
 'gene',
 'feature_is_filtered',
 'feature_name',
 'feature_reference',
 'feature_biotype',
 'feature_length',
 'feature_type']

In [10]:
print("Cells:", adata.n_obs)
print("Genes:", adata.n_vars)
print("Layers:", list(adata.layers.keys()))
print("Embeddings:", list(adata.obsm.keys()))
print("Raw available:", adata.raw is not None)

Cells: 47107
Genes: 25344
Layers: [None]
Embeddings: ['X_umap']
Raw available: True

In [11]:
for col in adata.obs.columns:
    if adata.obs[col].nunique() < 30:
        print("\n", col)
        print(adata.obs[col].value_counts(dropna=False))

 Patient
Patient
203    6296
146    4044
150    3888
136    2997
181    2703
151    2435
190    2041
75     2009
119    1858
74     1831
82     1682
283    1657
103    1602
156    1602
183    1530
11     1446
194    1335
105    1236
35     1187
182    1138
188     651
71      566
70      490
20      328
79      187
184     153
66      117
60       95
39        3
Name: count, dtype: int64

 Primary Site
Primary Site
Sigmoid            22112
Rectum             14938
Transverse          3288
Descending          2435
Cecum               1955
Hepatic Flexure     1657
Upper Rectum         566
Appendix             153
Splenic Flexure        3
Name: count, dtype: int64

 Sample Type
Sample Type
Non-Tumor     18117
Primary       16838
Metastasis    12152
Name: count, dtype: int64

 Site
Site
NaN           34955
Liver         10332
Lung            975
Chest Wall      799
Peritoneum       46
Name: count, dtype: int64

 Tumor Status
Tumor Status
Non-Tumor        21026
Primary Tumor    13929
Metastasis       12152
Name: count, dtype: int64

 Treatment
Treatment
True     33264
False    13843
Name: count, dtype: int64

 donor_id
donor_id
HTA8_6029    6296
HTA8_6017    4044
HTA8_6018    3888
HTA8_6016    2997
HTA8_6021    2703
HTA8_6019    2435
HTA8_6026    2041
HTA8_6010    2009
HTA8_6015    1858
HTA8_6009    1831
HTA8_6012    1682
HTA8_6028    1657
HTA8_6013    1602
HTA8_6020    1602
HTA8_6023    1530
HTA8_6001    1446
HTA8_6027    1335
HTA8_6014    1236
HTA8_6003    1187
HTA8_6022    1138
HTA8_6025     651
HTA8_6008     566
HTA8_6007     490
HTA8_6002     328
HTA8_6011     187
HTA8_6024     153
HTA8_6006     117
HTA8_6005      95
HTA8_6004       3
Name: count, dtype: int64

 development_stage_ontology_term_id
development_stage_ontology_term_id
HsapDv:0000162    6413
HsapDv:0000144    5929
HsapDv:0000139    5280
HsapDv:0000168    2997
HsapDv:0000149    2976
HsapDv:0000143    2763
HsapDv:0000172    2703
HsapDv:0000147    2009
HsapDv:0000164    1858
HsapDv:0000159    1831
HsapDv:0000167    1755
HsapDv:0000135    1682
HsapDv:0000133    1657
HsapDv:0000158    1602
HsapDv:0000146    1335
HsapDv:0000156    1187
HsapDv:0000138    1138
HsapDv:0000169     651
HsapDv:0000154     566
HsapDv:0000129     490
HsapDv:0000131     187
HsapDv:0000134      95
HsapDv:0000142       3
Name: count, dtype: int64

 sex_ontology_term_id
sex_ontology_term_id
PATO:0000384    24048
PATO:0000383    23059
Name: count, dtype: int64

 self_reported_ethnicity_ontology_term_id
self_reported_ethnicity_ontology_term_id
HANCESTRO:0590    32295
HANCESTRO:0612     5574
unknown            4179
HANCESTRO:0847     3114
HANCESTRO:0568     1945
Name: count, dtype: int64

 disease_ontology_term_id
disease_ontology_term_id
MONDO:0005575    28990
PATO:0000461     18117
Name: count, dtype: int64

 tissue_type
tissue_type
tissue    47107
Name: count, dtype: int64

 tissue_ontology_term_id
tissue_ontology_term_id
UBERON:0001159    15508
UBERON:0001052    11535
UBERON:0002107    10332
UBERON:0001157     2905
UBERON:0001158     2018
UBERON:0001153     1989
UBERON:0022277     1000
UBERON:0002048      975
UBERON:0016435      799
UBERON:0002358       46
Name: count, dtype: int64

 cell_type_ontology_term_id
cell_type_ontology_term_id
CL:0001064    26551
CL:4047018     6778
CL:0000151     5457
CL:0009043     2203
CL:1000347     2030
CL:0009039     1711
CL:4047052     1363
CL:0009041      828
CL:0009042      186
Name: count, dtype: int64

 assay_ontology_term_id
assay_ontology_term_id
EFO:0009922    47107
Name: count, dtype: int64

 suspension_type
suspension_type
cell    47107
Name: count, dtype: int64

 Author Cell Type
Author Cell Type
Primary Tumor           14399
Metastasis              12152
Absorptive Precursor     6778
Secretory Precursor      5457
ISC                      2203
Enterocytes              2030
Goblet                   1711
BEST4+ Enterocytes       1363
Tuft                      828
Enteroendocrine           186
Name: count, dtype: int64

 is_primary_data
is_primary_data
True    47107
Name: count, dtype: int64

 cell_type
cell_type
malignant cell                         26551
early colonocyte                        6778
secretory cell                          5457
intestinal crypt stem cell of colon     2203
colonocyte                              2030
colon goblet cell                       1711
BEST4+ colonocyte                       1363
tuft cell of colon                       828
enteroendocrine cell of colon            186
Name: count, dtype: int64

 assay
assay
10x 3' v3    47107
Name: count, dtype: int64

 disease
disease
colorectal cancer    28990
normal               18117
Name: count, dtype: int64

 sex
sex
male      24048
female    23059
Name: count, dtype: int64

 tissue
tissue
sigmoid colon               15508
rectum                      11535
liver                       10332
transverse colon             2905
descending colon             2018
caecum                       1989
hepatic flexure of colon     1000
lung                          975
chest wall                    799
peritoneum                     46
Name: count, dtype: int64

 self_reported_ethnicity
self_reported_ethnicity
European American    32295
Hispanic or Latin     5574
unknown               4179
Asian                 3114
African American      1945
Name: count, dtype: int64

 development_stage
development_stage
68-year-old stage    6413
50-year-old stage    5929
45-year-old stage    5280
74-year-old stage    2997
55-year-old stage    2976
49-year-old stage    2763
78-year-old stage    2703
53-year-old stage    2009
70-year-old stage    1858
65-year-old stage    1831
73-year-old stage    1755
41-year-old stage    1682
39-year-old stage    1657
64-year-old stage    1602
52-year-old stage    1335
62-year-old stage    1187
44-year-old stage    1138
75-year-old stage     651
60-year-old stage     566
35-year-old stage     490
37-year-old stage     187
40-year-old stage      95
48-year-old stage       3
Name: count, dtype: int64